# Análisis del balance de materia en fabricación de queso mediante `Python`

In [1]:
import os, sys
import pandas as pd
import datetime
import numpy as np
import matplotlib.pyplot as plt

In [2]:
import seaborn as sns
sns.set_style("whitegrid")

In [30]:
url_datos = 'https://raw.githubusercontent.com/juanriera/master-queseria/master/datos/fab_queso_bm.csv'

try:
    df = pd.read_csv(url_datos, decimal = ",", sep=';', encoding='ISO-8859-1')
    print("¡Archivo ", url_datos," cargado correctamente!")
    print(f"Dimensiones de los datos: {df.shape}")
except Exception as e:
    print(f"Error al cargar el archivo: {e}")

¡Archivo  https://raw.githubusercontent.com/juanriera/master-queseria/master/datos/fab_queso_bm.csv  cargado correctamente!
Dimensiones de los datos: (448, 20)

In [31]:
# crear index con fecha
df['fecha_index'] = pd.to_datetime(
    df['fecha'], 
    format='%d/%m/%Y',  # Formato Día/Mes/Año confirmado
    errors='coerce'     # Clave: convierte los valores que no puede leer a NaT (Not a Time)
)
# 2. Limpiar NaT y establecer el índice
df.dropna(subset=['fecha_index'], inplace=True)
df.set_index('fecha_index', inplace=True)
df.sort_index(inplace=True)

In [32]:
# Crear una lista de los nombres de recetas únicos en el orden en que aparecen
recetas_unicas_ordenadas = df['receta'].drop_duplicates().tolist()

# Crear un diccionario para mapear cada nombre único a su número secuencial
# Ejemplo: {'IQM pequeño': 1, 'Oveja DO 3 kg': 2, ...}
mapa_secuencial = {nombre: i + 1 for i, nombre in enumerate(recetas_unicas_ordenadas)}

# Asignar el nuevo número secuencial a la nueva columna
df['num_receta'] = df['receta'].map(mapa_secuencial)

# Finalmente, crear el formato de texto 'receta X'
df['receta'] = 'receta ' + df['num_receta'].astype(str)

df.to_csv("fab_queso_bm_recetas_secuenciales.csv", index=False, decimal = ",", sep=';')

In [29]:
df.head()

                  fecha    receta  ...  sal_queso  num_receta
fecha_index                        ...
2022-02-22   22/02/2022  receta 1  ...       1.32           1
2022-02-22   22/02/2022  receta 2  ...       1.52           2
2022-02-22   22/02/2022  receta 3  ...       1.64           3
2022-02-22   22/02/2022  receta 4  ...        NaN           4
2022-02-22   22/02/2022  receta 5  ...       1.47           5

[5 rows x 21 columns]

In [20]:
df.dtypes

fecha                         object
receta                        object
litros_past                    int64
kg_cuba                      float64
mg_cuba                      float64
mp_cuba                      float64
lactosa_cuba                 float64
ph_cuajado                   float64
ph_inicio_moldeo_cuba        float64
ph_final_moldeo_cuba         float64
Formato de queso              object
ph_inicio_moldeo_queso       float64
ph_inicio_desmoldeo_queso    float64
ph_fin_desmoldeo_queso       float64
tiempo_salado                 object
mg_salida_salmuera           float64
ph_salida_salmuera           float64
EST salida salmuera          float64
peso_queso_total             float64
sal_queso                    float64
dtype: object

In [22]:
df.describe()

        litros_past       kg_cuba  ...  peso_queso_total   sal_queso
count    441.000000    441.000000  ...        441.000000  364.000000
mean   11291.632653  11645.731973  ...       9145.808753    1.389505
std     2147.006385   2207.640726  ...       6307.250330    0.350672
min     6780.000000   7500.000000  ...        398.350000    0.000000
25%     9220.000000   9450.370000  ...       3965.000000    1.200000
50%    11530.000000  12000.000000  ...       7376.000000    1.390000
75%    13030.000000  13281.420000  ...      13283.000000    1.602500
max    15830.000000  16452.760000  ...      28264.000000    2.610000

[8 rows x 16 columns]

In [25]:
df.head()

                  fecha    receta  ...  sal_queso  num_receta
fecha_index                        ...
2022-02-22   22/02/2022  receta 1  ...       1.32           1
2022-02-22   22/02/2022  receta 2  ...       1.52           2
2022-02-22   22/02/2022  receta 3  ...       1.64           3
2022-02-22   22/02/2022  receta 4  ...        NaN           4
2022-02-22   22/02/2022  receta 5  ...       1.47           5

[5 rows x 21 columns]

In [34]:
df['formato'].unique()

KeyError: 'formato'